Name=input("Enter your name: ")
Location=input("Enter your destination: ")
Location2=input("Enter the place you were coming from: ")
print("There was once a person named "+ Name + ", Walking back from " + Location2)
print("It was a normal day, " + Name + " was walking down the street, heading towards their " + Location)
Monster=input("Enter your Monster name: ")
print("Until suddenly, " + Name + " saw " + Monster + " coming out of " + Location)
Verb1=input("Type a verb for going away from something: ")
print(Name + " then decided to " + Verb1 + " for their life")
People=input("Write someone you care about: ")
print(Name + " then realised that their " + People + " was still in the " + Location)
Action=input("Enter a heroic word: ")
print(Name + " ran towards " + Monster + " in order to " + Action + " the monster")